### ISSUE TITLE
AIMNet2 Performance near TS

### ISSUE THREAD

**Issue by kangmg** [isayevlab/AIMNet2#29]
![image](https://github.com/user-attachments/assets/9f164ef8-7353-4ae1-9d4c-aea78d590a58)

I have tested a simple PES calculation for the Diels-Alder reaction using the following models:

AIMNet2
torchani models (ani-1x, ani-2x, ani-ccx, ani-xnr)
DFT calculations as the target theory for each ML potential

The results indicate that AIMNet2 shows good predictive performance even near the transition state (TS).

My question is, what might be the reason AIMNet2 predicts well near the TS compared to ANI models? Additionally, does AIMNet2 generally predict well near the TS?

In a past presentation about AIMNet2 [video](https://youtu.be/huMRyYGa2gs?feature=shared&t=1155), a TS-targeted model called RxnAIMNet is mentioned. Could you please clarify if this is the same model as the current AIMNet2?

Sincerely,
Kangmg

**Comment by zubatyuk** [comment]
Hi Kangmg,
Thank you for a feedback.

> My question is, what might be the reason AIMNet2 predicts well near the TS compared to ANI models?

AIMNet2 is more sophisticated model, trained on a larger corpus of data.
Btw, ANI1-ccx does well on this reaction. And AIMNet2_B97-3c does poor job, probably due to deficiency of GGA DFT reference.

> Additionally, does AIMNet2 generally predict well near the TS?

In many (one can say most) cases it is decent. Models trained on datasets with emphasis on reaction paths certainly might be noticeably better.

> Could you please clarify if this is the same model as the current AIMNet2?

This model is under development. Up to my understanding, it has the same architecture, maybe with very minor charges. The training dataset specifically targets diverse set of reactions.
